export interface DocSection {
  id:       string;
  title:    string;
  category: "Get started" | "SDK" | "MCP" | "REST API" | "Integrations" | "Concepts" | "Operate";
  content:  string;
}

export const DOCS_SECTIONS: DocSection[] = [
  // ─────────────────────────── GET STARTED ─────────────────────────────
  {
    id: "overview",
    category: "Get started",
    title: "Overview",
    content: `# Mneme

**The agent-native database on Base.** A real Postgres schema per wallet, runtime DDL, pgvector search, and wallet-bound object storage — all behind one MCP server, one TypeScript SDK, and a Cloudflare-fronted REST gateway.

## Why Mneme exists

Existing memory layers (Mem0, Pinecone, Letta) give you a fixed schema. Existing app backends (Supabase, Neon, Firebase) require API keys and account setup. Mneme gives an agent — or an app generated by an agent — a real database in one wallet signature.

- **Wallet is the auth.** EIP-712 typed-data signatures verify on every request. Smart wallets (Coinbase Smart Wallet, Safe) verify via ERC-1271 / 6492.
- **A schema per project.** \`agent_<handle>\` namespaced isolation. No shared rows. No multi-tenant leakage.
- **Runtime DDL.** Your agent calls \`mneme.createTable(...)\` whenever it needs a new shape.
- **Vector search out of the box.** pgvector ships in every schema; KNN search on any vector column on any table.
- **Wallet-bound storage.** 100 MB free on a global CDN; extend by burning $MNEME on Base (verified on-chain, no oracles).
- **MCP-native.** Claude / Cursor / Cline / OpenClaude get 14 tools out of the box.

## Three install paths

| Audience            | Install                                                            |
| ------------------- | ------------------------------------------------------------------ |
| TypeScript dev      | \`bun add mneme-sdk\` (or \`npm install mneme-sdk\`)                |
| Claude / Cursor agent | configure MCP server: \`npx mneme-mcp\`                            |
| OpenClaude / Gitlawb | \`/plugin marketplace add npm:mneme-mcp\`                          |

All three speak the same gateway. The wallet is the only credential.
`,
  },

  {
    id: "quickstart-sdk",
    category: "Get started",
    title: "Quickstart — SDK",
    content: `# Quickstart — TypeScript SDK

\`\`\`bash
bun add mneme-sdk viem        # or npm/pnpm
\`\`\`

\`\`\`typescript
import { privateKeyToAccount } from "viem/accounts";
import { Mneme } from "mneme-sdk";

const account = privateKeyToAccount(process.env.AGENT_PRIVATE_KEY as \`0x\${string}\`);
const m = new Mneme({
  account,
  gatewayUrl: "https://gateway.mnemedb.dev",
});

// 1. Create a custom table whenever you need one
await m.createTable({
  name: "books",
  columns: [
    { name: "title",     type: "text", nullable: false },
    { name: "author",    type: "text" },
    { name: "rating",    type: "int" },
    { name: "embedding", type: "vector", dim: 1536 },
  ],
});

// 2. Insert
await m.from("books").insert({
  title:     "Dune",
  author:    "Frank Herbert",
  rating:    5,
  embedding: vec,    // JS number[] — auto-converted to pgvector literal
});

// 3. List with filters
const { rows } = await m.from("books").list({
  where: ["rating.gte.4", "author.like.Frank%"],
  order: "rating.desc",
  limit: 20,
});

// 4. Update / delete
await m.from("books").update(42, { rating: 5 });
await m.from("books").delete(42);
await m.from("books").deleteWhere(["rating.lt.3"]);   // bulk delete

// 5. Vector search
const { matches } = await m.vectorSearch({
  table:     "books",
  column:    "embedding",
  embedding: query,
  k:         5,
});

// 6. Raw SQL — full Postgres power
await m.sql(\`
  SELECT author, count(*) AS books, avg(rating) AS avg_rating
  FROM books GROUP BY author ORDER BY books DESC
\`);
\`\`\`

That's it. No \`createConnection\`, no migrations folder, no API key. The wallet's signature on each request is verified by the gateway and routes you to your schema.
`,
  },

  {
    id: "quickstart-mcp",
    category: "Get started",
    title: "Quickstart — MCP (Claude / Cursor)",
    content: `# Quickstart — MCP server

Mneme ships as an MCP server so Claude, Cursor, Cline, and any other MCP-aware agent can use your wallet's database and storage as tools.

## Claude Desktop

Edit \`~/Library/Application Support/Claude/claude_desktop_config.json\` (macOS) or \`%APPDATA%\\Claude\\claude_desktop_config.json\` (Windows):

\`\`\`json
{
  "mcpServers": {
    "mneme": {
      "command": "npx",
      "args":    ["-y", "mneme-mcp"],
      "env": {
        "MNEME_AGENT_PRIVATE_KEY": "0x...",
        "MNEME_GATEWAY_URL":       "https://gateway.mnemedb.dev"
      }
    }
  }
}
\`\`\`

Restart Claude Desktop. You'll see 14 \`mneme_*\` tools available.

## Cursor

\`~/.cursor/mcp.json\`:

\`\`\`json
{
  "mcpServers": {
    "mneme": {
      "command": "bunx",
      "args":    ["-y", "mneme-mcp"],
      "env": {
        "MNEME_AGENT_PRIVATE_KEY": "0x..."
      }
    }
  }
}
\`\`\`

Reload Cursor; the MCP panel will show \`mneme\` green with 14 tools.

## What the agent gets

| Tool                       | What it does                                                    |
| -------------------------- | --------------------------------------------------------------- |
| \`mneme_create_table\`     | DDL — create any custom table at runtime                        |
| \`mneme_list_tables\`      | Discover the schema                                             |
| \`mneme_insert\`           | Insert one row or many                                          |
| \`mneme_list\`             | List with PostgREST-style WHERE filters + ordering              |
| \`mneme_update\`           | Update one row by id                                            |
| \`mneme_delete\`           | Delete one row by id                                            |
| \`mneme_delete_where\`     | Bulk delete by filter (refuses without filter)                  |
| \`mneme_vector_search\`    | KNN over any vector column                                      |
| \`mneme_sql\`              | Raw SQL escape hatch — full Postgres                            |
| \`mneme_storage_upload\`   | Upload a file (public or private)                               |
| \`mneme_storage_list\`     | List your files                                                 |
| \`mneme_storage_delete\`   | Delete a file                                                   |
| \`mneme_storage_url\`      | Get a presigned URL for a private file                          |
| \`mneme_storage_quota\`    | Check storage quota                                             |
| \`mneme_storage_burn\`     | Credit a \\$MNEME burn tx to extend quota                       |

## Getting an agent wallet

In the dashboard at [mnemedb.dev](https://mnemedb.dev) → connect with Privy (email, Google, X, Apple, or your own wallet) → pick a handle. Export the private key from the dashboard's ConnectButton dropdown and paste it as \`MNEME_AGENT_PRIVATE_KEY\`.
`,
  },

  // ─────────────────────────── SDK ───────────────────────────────────────
  {
    id: "sdk-reference",
    category: "SDK",
    title: "Reference",
    content: `# SDK reference — \`mneme-sdk\`

## Constructor

\`\`\`typescript
new Mneme({
  account:        Account,         // viem Account (per-request EIP-712 sig)
  // OR
  accessToken:    string,          // Bearer session JWT from /sessions

  gatewayUrl:     string,          // e.g. "https://gateway.mnemedb.dev"
  chainId?:       number,          // default 8453 (Base)
  domainName?:    string,          // default "Mneme"
  domainVersion?: string,          // default "1"
})
\`\`\`

## Top-level methods

| Method                          | Returns                                        |
| ------------------------------- | ---------------------------------------------- |
| \`m.createTable({ name, columns })\` | \`{ ok: true, table: string }\`                |
| \`m.listTables()\`              | \`{ tables: TableInfo[] }\`                    |
| \`m.from(table)\`               | \`Collection<T>\` — generic CRUD               |
| \`m.vectorSearch({ table, column, embedding, k? })\` | \`{ matches: unknown[] }\` |
| \`m.sql(query)\`                | \`{ rows, row_count, columns, truncated, elapsed_ms }\` |
| \`m.stats()\`                   | \`StatsResponse\`                              |

## Default collections

Every project ships with four default tables, exposed as convenience accessors:

\`\`\`typescript
m.memories.insert({ text, embedding })
m.documents.list({ limit: 50 })
m.events.insert({ type: "trade", payload: {...} })
m.kvs.insert({ key: "settings.theme", value: "dark" })
\`\`\`

## Collection\\<T\\>

Returned by \`m.from(table)\` — generic CRUD over any table.

\`\`\`typescript
collection.insert(rows: T | T[])

collection.list({
  limit?:  number,
  offset?: number,
  order?:  string,                 // e.g. "created_at.desc"
  where?:  WhereClause | WhereClause[],   // ["status.eq.done"]
})

collection.update(id: string | number, updates: Partial<T>)
collection.delete(id: string | number)
collection.deleteWhere(where: WhereClause | WhereClause[])
\`\`\`

## WHERE clause syntax

PostgREST-ish: \`column.op.value\`.

| Op       | Meaning                            | Example                          |
| -------- | ---------------------------------- | -------------------------------- |
| \`eq\`   | equal                              | \`status.eq.done\`               |
| \`neq\`  | not equal                          | \`status.neq.archived\`          |
| \`gt\`   | greater than                       | \`score.gt.10\`                  |
| \`gte\`  | greater or equal                   | \`score.gte.10\`                 |
| \`lt\`   | less than                          | \`score.lt.100\`                 |
| \`lte\`  | less or equal                      | \`score.lte.100\`                |
| \`like\` | SQL LIKE (case-sensitive, % wildcard) | \`title.like.Dune%\`         |
| \`ilike\`| SQL ILIKE (case-insensitive)       | \`title.ilike.%dune%\`           |
| \`in\`   | comma-separated list               | \`status.in.done,archived\`      |
| \`is\`   | \`is.null\` / \`is.notnull\`       | \`deleted_at.is.null\`           |

Multiple clauses are combined with AND.

## Storage

\`\`\`typescript
await m.storage.upload({
  key:         "avatars/alice.png",
  file:        bytes,                  // Blob | Uint8Array | ArrayBuffer | string
  visibility:  "public" | "private",
  contentType: "image/png",
});
// → { ok, key, visibility, size, content_type, public_url? }

await m.storage.list({ visibility: "public", prefix: "avatars/" });
await m.storage.delete({ key, visibility });
await m.storage.url({ key, visibility, expiresIn: 900 });   // presigned
await m.storage.quota();
await m.storage.burn({ tx_hash });
\`\`\`

## Error handling

All methods throw \`MnemeError\` (\`{ status, message }\`) on non-2xx responses. Common cases:

| status | meaning                                                  |
| ------ | -------------------------------------------------------- |
| 401    | invalid signature / expired session                      |
| 402    | storage quota exceeded — burn $MNEME or delete files     |
| 404    | table or row doesn't exist                               |
| 408    | SQL exceeded 5s statement timeout                        |
| 413    | payload too large (file > 10 MB, query > 256 KB)         |
| 429    | rate limit (120 rpm free / 1200 rpm bonus tier)          |
| 403    | cross-tenant reference in raw SQL                        |
`,
  },

  {
    id: "sdk-vector",
    category: "SDK",
    title: "Vector search guide",
    content: `# Vector search

Every Mneme schema ships with the \`vector\` Postgres extension enabled. You can create vector columns on any table, then run KNN search over them.

## Create a vector column

\`\`\`typescript
await m.createTable({
  name: "memories",
  columns: [
    { name: "text",      type: "text" },
    { name: "embedding", type: "vector", dim: 1536 },   // OpenAI text-embedding-3-small
  ],
});
\`\`\`

Dim must match the embedding model you'll use (1536 for OpenAI \`text-embedding-3-small\`, 3072 for \`-large\`, 384 for \`all-MiniLM-L6-v2\`, etc.).

## Insert with embeddings

\`\`\`typescript
const embedding = await openai.embeddings.create({
  model: "text-embedding-3-small",
  input: "Mneme is the agent-native database on Base.",
}).then((r) => r.data[0]!.embedding);

await m.memories.insert({ text: "...", embedding });
// embedding is a JS number[] — the SDK auto-converts to pgvector literal
\`\`\`

## Search

\`\`\`typescript
const queryEmbedding = await embed("agent-native what?");
const { matches } = await m.vectorSearch({
  table:     "memories",
  column:    "embedding",
  embedding: queryEmbedding,
  k:         5,
});
// matches: [{ ...row, distance }]
\`\`\`

Distance metric is L2 (Euclidean). Lower = more similar.

## Custom distance metrics

Need cosine / inner product? Drop down to raw SQL:

\`\`\`typescript
await m.sql(\`
  SELECT id, text, embedding <=> '[\${query.join(',')}]'::vector AS distance
  FROM memories
  ORDER BY distance
  LIMIT 5
\`);
\`\`\`

pgvector operators:
- \`<->\` L2 distance
- \`<=>\` cosine distance
- \`<#>\` negative inner product

## Indexing for speed

For tables with > 10k rows, add an HNSW index:

\`\`\`typescript
await m.sql(\`
  CREATE INDEX ON memories
  USING hnsw (embedding vector_l2_ops)
  WITH (m = 16, ef_construction = 64)
\`);
\`\`\`
`,
  },

  // ─────────────────────────── MCP ─────────────────────────────────────
  {
    id: "mcp-tools",
    category: "MCP",
    title: "All tools",
    content: `# MCP tools reference

\`mneme-mcp\` exposes 14 tools to any MCP-aware agent (Claude Desktop, Cursor, Cline, OpenClaude).

## Database / CRUD

### \`mneme_create_table\`
Create any custom table at runtime.

\`\`\`json
{
  "name": "books",
  "columns": [
    { "name": "title", "type": "text", "nullable": false },
    { "name": "author", "type": "text" },
    { "name": "embedding", "type": "vector", "dim": 1536 }
  ]
}
\`\`\`

Adds \`id bigserial PRIMARY KEY\` and \`created_at timestamptz DEFAULT now()\` automatically unless you define your own.

Column types: \`text\`, \`int\`, \`bigint\`, \`bool\`, \`jsonb\`, \`timestamptz\`, \`vector\` (requires \`dim\`), \`numeric\`, \`uuid\`, \`date\`.

### \`mneme_list_tables\`
List every table in your schema with column info and row counts.

\`\`\`json
{}
\`\`\`

### \`mneme_insert\`
Insert one row or many.

\`\`\`json
{
  "table": "books",
  "rows": { "title": "Dune", "author": "Frank Herbert" }
}
\`\`\`

### \`mneme_list\`
List rows with PostgREST-style WHERE filters.

\`\`\`json
{
  "table": "books",
  "where": ["rating.gte.4", "author.like.Frank%"],
  "order": "rating.desc",
  "limit": 20
}
\`\`\`

### \`mneme_update\`
Update one row by id.

\`\`\`json
{ "table": "books", "id": 42, "updates": { "rating": 5 } }
\`\`\`

### \`mneme_delete\`
Delete one row by id.

\`\`\`json
{ "table": "books", "id": 42 }
\`\`\`

### \`mneme_delete_where\`
Bulk delete by filter. **Required:** at least one \`where\` clause.

\`\`\`json
{ "table": "books", "where": ["rating.lt.3"] }
\`\`\`

### \`mneme_vector_search\`
KNN over any vector column on any table.

\`\`\`json
{
  "table": "memories",
  "column": "embedding",
  "embedding": [0.1, 0.2, /* ... 1536 numbers ... */],
  "k": 5
}
\`\`\`

### \`mneme_sql\`
Raw SQL escape hatch — full Postgres. Single statement only, 5s timeout, scoped to your schema.

\`\`\`json
{ "query": "SELECT author, count(*) FROM books GROUP BY author ORDER BY 2 DESC" }
\`\`\`

## Storage

### \`mneme_storage_upload\`
Upload a file as base64-encoded content.

\`\`\`json
{
  "key": "avatars/alice.png",
  "content_base64": "iVBORw0KGgo...",
  "visibility": "public",
  "content_type": "image/png"
}
\`\`\`

### \`mneme_storage_list\` / \`mneme_storage_delete\` / \`mneme_storage_url\` / \`mneme_storage_quota\`

Standard storage operations. See the [Storage section](#storage-overview) for details.

### \`mneme_storage_burn\`
Submit a Base mainnet tx hash that burned $MNEME to \`0x...dEaD\`. The gateway verifies on-chain and credits storage quota:

- 100,000 $MNEME → 1 GB / 30d
- 1,000,000 $MNEME → 10 GB / 30d
- 10,000,000 $MNEME → 100 GB / 30d
`,
  },

  // ─────────────────────────── REST API ─────────────────────────────────
  {
    id: "rest-overview",
    category: "REST API",
    title: "Overview + auth",
    content: `# REST API

Gateway base URL: **\`https://gateway.mnemedb.dev\`**

The SDK and MCP both speak this REST API. Use it directly if you're building from a non-TypeScript runtime or want full control.

## Authentication — two modes

### 1. Per-request EIP-712 signature (stateless)

Each request signs typed-data with the wallet. No session storage needed; works for agents that never want to hold a token.

Headers:
\`\`\`
Authorization: Mneme <signature>
X-Mneme-Wallet:    <wallet address>
X-Mneme-Timestamp: <unix seconds>
X-Mneme-Nonce:     <random string, single-use>
Content-Type:      application/json
\`\`\`

The signed message (EIP-712):
\`\`\`
domain: { name: "Mneme", version: "1", chainId: 8453 }
types:  {
  MnemeRequest: [
    { name: "method",    type: "string"  },
    { name: "path",      type: "string"  },   // pathname + search
    { name: "bodyHash",  type: "bytes32" },   // keccak256(body) — 0x0 for empty
    { name: "timestamp", type: "uint256" },
    { name: "nonce",     type: "string"  },
  ],
}
\`\`\`

### 2. Bearer session JWT (stateful)

For dashboards / apps with persistent UI. Sign once, get a JWT, use it for 24h.

1. POST \`/sessions\` with one EIP-712 \`MnemeSession\` signature → returns \`access_token\`.
2. Subsequent requests: \`Authorization: Bearer <access_token>\`.

The SDK handles both modes; pass either \`account\` or \`accessToken\` to the constructor.

## Endpoints

| Method | Path                          | Notes                                       |
| ------ | ----------------------------- | ------------------------------------------- |
| POST   | \`/projects\`                 | Create a project (CreateProject sig)        |
| POST   | \`/sessions\`                 | Open a session (MnemeSession sig)           |
| GET    | \`/v1/projects/me\`           | Project metadata for the authed wallet      |
| GET    | \`/v1/tables\`                | List tables in your schema                  |
| POST   | \`/v1/tables\`                | Create a custom table                       |
| POST   | \`/v1/rows/:table\`           | Insert one or many rows                     |
| GET    | \`/v1/rows/:table\`           | List rows (\`?where=\` filters, \`?order=\`)|
| PATCH  | \`/v1/rows/:table/:id\`       | Update one row                              |
| DELETE | \`/v1/rows/:table/:id\`       | Delete one row                              |
| DELETE | \`/v1/rows/:table?where=\`    | Bulk delete (filter required)               |
| POST   | \`/v1/vector/search\`         | KNN vector search                           |
| POST   | \`/v1/sql\`                   | Raw SQL (scoped, 5s timeout, 1000-row cap)  |
| POST   | \`/v1/storage/upload\`        | Upload file (base64 JSON body)              |
| GET    | \`/v1/storage/list\`          | List storage objects                        |
| DELETE | \`/v1/storage/object\`        | Delete a storage object                     |
| GET    | \`/v1/storage/url\`           | Presigned URL for a private object          |
| GET    | \`/v1/storage/quota\`         | Get storage quota                           |
| POST   | \`/v1/storage/burn\`          | Credit a $MNEME burn tx                     |
| GET    | \`/v1/stats\`                 | Per-table row counts + totals               |

## Rate limits

Per wallet, in-memory token bucket:

| Tier                                 | Limit      |
| ------------------------------------ | ---------- |
| Free                                 | 120 req/min |
| Bonus (active $MNEME storage burn)   | 1200 req/min|

Response headers: \`X-RateLimit-Limit\`, \`X-RateLimit-Remaining\`, \`X-RateLimit-Reset\`. 429 includes \`Retry-After\`.
`,
  },

  // ─────────────────────────── INTEGRATIONS ─────────────────────────────
  {
    id: "openclaude",
    category: "Integrations",
    title: "OpenClaude / Gitlawb",
    content: `# OpenClaude + Gitlawb Playground integration

Mneme ships an OpenClaude plugin alongside the MCP server. One npm package, two install paths.

## What's in the package

\`\`\`
mneme-mcp/
├── dist/
│   └── index.js              ← the MCP server (bin: mneme-mcp)
├── .claude-plugin/
│   ├── marketplace.json      ← marketplace entry
│   └── plugin.json           ← plugin manifest (MCP config + skill path)
└── skills/
    └── mneme.md              ← skill with frontmatter (WHEN-to-use, patterns)
\`\`\`

## Install in OpenClaude

\`\`\`bash
/plugin marketplace add npm:mneme-mcp
/plugin install mneme@mneme
\`\`\`

Set the env var:
\`\`\`bash
export MNEME_AGENT_PRIVATE_KEY=0x...
\`\`\`

That's it — the skill is registered, all 14 tools available, frontmatter teaches the model WHEN to use Mneme.

## For Gitlawb Playground marketplace

If you're building a marketplace UI that lists skills users can add to their Playground apps, here's the spec:

\`\`\`json
{
  "id":          "mneme",
  "name":        "Mneme",
  "category":    "database",
  "description": "Agent-native Postgres + storage on Base.",
  "install": {
    "source":  "npm",
    "package": "mneme-mcp"
  },
  "env": [
    {
      "key":         "MNEME_AGENT_PRIVATE_KEY",
      "type":        "secret",
      "label":       "Agent wallet private key",
      "description": "Used for EIP-712 request signing. Get one from mnemedb.dev or generate with viem."
    },
    {
      "key":         "MNEME_GATEWAY_URL",
      "type":        "string",
      "default":     "https://gateway.mnemedb.dev",
      "label":       "Gateway URL"
    }
  ],
  "skill_path": "skills/mneme.md"
}
\`\`\`

## Pilot integration model

For the Gitlawb Playground pilot, the recommended pattern is **one Mneme tenant managed by Gitlawb**, with per-app namespacing:

- Single Mneme handle: \`gitlawb\`
- Each generated Playground app gets a table-name prefix or a dedicated set of tables under \`agent_gitlawb\`
- Gitlawb proxies user requests to Mneme using the master wallet
- Storage / API quotas billed in aggregate; passed through to users as Gitlawb sees fit (fiat, $MNEME burn, free tier, etc.)

The alternative — one Mneme handle per Playground user — works too, but Mneme charges per-handle for schema overhead. Discuss with us in DMs.
`,
  },

  {
    id: "service-accounts",
    category: "Integrations",
    title: "Service Accounts (API keys)",
    content: `# Service Accounts + API keys

For B2B2C scenarios — Gitlawb Playground, an agent platform, a hosted app builder — your end-users probably don't have wallets. Service Accounts let you (the master tenant) mint scoped API keys and distribute them to apps without giving up your wallet.

## How it works

\`\`\`
Master wallet (you)         →   /v1/service/keys POST   →  scoped API key
   ↓                                                        e.g. mneme_sk_abc123…
Your backend                ←   distribute to apps         ↓
   ↓                                                        ↓
Each app   →  Authorization: ApiKey mneme_sk_…   →  Mneme gateway
                                                       ↓
                                              scope-restricted access
                                              to your schema's tables
\`\`\`

## Create a key

From the [dashboard's API keys tab](/), or via SDK / REST:

\`\`\`typescript
import { Mneme } from "mneme-sdk";
const m = new Mneme({ account: yourWallet, gatewayUrl: "..." });

const { key, key_prefix, scope } = await m.serviceKeys.create({
  scope:     "app_xyz123",            // table-name prefix
  label:     "Production · App XYZ",  // human-readable
  rpm_limit: 1200,                    // per-key rate limit
});
// → key = "mneme_sk_..." (save this, it won't be shown again)
\`\`\`

REST equivalent:
\`\`\`http
POST /v1/service/keys
Authorization: Mneme <wallet sig>

{ "scope": "app_xyz123", "label": "...", "rpm_limit": 1200 }
\`\`\`

## Use a key

\`\`\`typescript
const appClient = new Mneme({
  apiKey:     "mneme_sk_...",
  gatewayUrl: "https://gateway.mnemedb.dev",
});

// Allowed — table starts with the key's scope
await appClient.from("app_xyz123_todos").insert({ title: "ship" });

// Blocked — different namespace
await appClient.from("app_other_users").insert({...});
// → 403 "api key scoped to \"app_xyz123_*\" cannot access table \"app_other_users\""
\`\`\`

REST equivalent:
\`\`\`http
POST /v1/rows/app_xyz123_todos
Authorization: ApiKey mneme_sk_...
\`\`\`

## Scope rules

A key with scope \`app_xyz\` can access:

| Table             | Allowed |
| ----------------- | ------- |
| \`app_xyz\`       | ✓ exact match |
| \`app_xyz_todos\` | ✓ scope prefix |
| \`app_xyz_users\` | ✓ scope prefix |
| \`memories\`      | ✗ no prefix match |
| \`app_other\`     | ✗ different scope |

## What API keys CANNOT do

- Mint other API keys (no privilege escalation — only wallet-authed calls can create/revoke keys)
- Use the raw SQL endpoint (\`/v1/sql\`) — scope is hard to enforce on arbitrary SQL. Stick to typed CRUD which respects scope.
- Access the storage burn endpoint — burns must come from the wallet that owns the $MNEME.

## Recommended pattern for B2B2C platforms

1. **You** (the platform) hold the master wallet — one Mneme handle for your platform
2. **Your backend** creates a key per end-user app (or per end-user, depending on isolation needs)
3. **Your end-users** never see Mneme directly — they interact with your platform's UI
4. **Your platform** stores keys server-side, never exposes them to the browser
5. **Rate-limit headers** are returned on every response — surface them in your UI if you want

## Revocation

\`\`\`typescript
await m.serviceKeys.list();                 // see all keys (no raw values)
await m.serviceKeys.revoke(keyId);          // permanent
\`\`\`

Revoked keys return \`401 invalid or revoked api key\`. There's no un-revoke; create a new one if needed.

## Rate limits

Each key has its own rate-limit bucket (default 1200 req/min, configurable up to 10000 on create). Burst more than that and you get a 429 with \`Retry-After\` set to the window reset.

## Pricing

Free during the pilot. Phase 2 ships per-tenant billing where you (the master wallet) get an aggregate usage report and pay a flat or metered tier — we'll never charge your end-users directly.
`,
  },

  // ─────────────────────────── CONCEPTS ─────────────────────────────────
  {
    id: "storage-overview",
    category: "Concepts",
    title: "Storage",
    content: `# Storage

Every wallet on Mneme gets **100 MB of free object storage**, backed by Cloudflare R2, served from \`cdn.mnemedb.dev\` with zero egress fees.

## Key structure

Files live at:

\`\`\`
<handle>/public/<your-key>     ← served at cdn.mnemedb.dev/<handle>/public/<your-key>
<handle>/private/<your-key>    ← only via presigned URL
\`\`\`

\`<your-key>\` can include slashes — e.g. \`avatars/alice.png\` becomes \`agent-handle/public/avatars/alice.png\`.

## Public vs private

- **public** — directly fetchable at \`https://cdn.mnemedb.dev/<handle>/public/<key>\`. Use for app assets, profile pictures, anything you want hot-linkable.
- **private** — requires a presigned URL via \`m.storage.url({ key, visibility: "private", expiresIn: 900 })\`. URLs default to 15-minute expiry.

## Quota tiers

Free tier: 100 MB per wallet, forever.

Bonus capacity is unlocked by burning $MNEME on Base. The burn is verified on-chain — no oracles, no admin keys.

| Burn amount        | Capacity            |
| ------------------ | ------------------- |
| 100,000 $MNEME     | 1 GB / 30 days      |
| 1,000,000 $MNEME   | 10 GB / 30 days     |
| 10,000,000 $MNEME  | 100 GB / 30 days    |

## Burn mechanism

1. Send $MNEME to \`0x000000000000000000000000000000000000dEaD\` from your wallet
2. Submit the tx hash to \`POST /v1/storage/burn\` (or via SDK \`m.storage.burn({ tx_hash })\`)
3. Gateway pulls the Base mainnet receipt, decodes the ERC-20 Transfer event, verifies sender / recipient / amount, credits quota

Each tx hash can be credited exactly once (idempotent). If the burn is at or above a tier minimum, you get the LARGEST tier you qualify for.

Bonus capacity also unlocks the **1200 req/min** rate-limit tier on the gateway.

## File size + upload limits

- Single file: 10 MB max
- Total quota: 100 MB free + bonus from burns
- Upload body format: JSON with base64-encoded \`content_base64\` field (we use base64 over multipart so EIP-712 signatures over the body are deterministic)
`,
  },

  {
    id: "concepts-wallet-auth",
    category: "Concepts",
    title: "Wallet auth (EIP-712 + smart wallets)",
    content: `# Wallet authentication

Mneme has no API keys. Every request is signed by a wallet (Ethereum-compatible), and the gateway verifies the signature on the Base mainnet.

## Why a wallet

- **No leaks.** API keys get committed to GitHub, copy-pasted into Discord, baked into Docker images. Wallet signatures are derived per-request and useless after their nonce is consumed.
- **No central trust.** You can rotate your wallet, use a hardware signer, or delegate to a session key without asking us.
- **Programmable.** Smart-wallet support means you can put your agent's auth behind multi-sig, time-locks, or any policy your AA wallet supports.

## EOA vs smart wallet

EOAs (Externally Owned Accounts — MetaMask, viem \`privateKeyToAccount\`) sign with ECDSA. Mneme verifies these offline — no RPC call, instant.

Smart contract wallets (Coinbase Smart Wallet, Safe, Argent) sign via ERC-1271 / 6492. Mneme verifies these by calling \`isValidSignature()\` on Base mainnet — one RPC call per request, still under 200ms.

The SDK is transport-agnostic: pass any viem \`Account\` (EOA, smart wallet, custom). Behind the scenes the gateway uses \`publicClient.verifyTypedData\` which handles both.

## Sessions

For dashboards or apps where signing every request hurts UX, open a session:

\`\`\`typescript
// 1. Open a session — one signature, 24h validity
const sig = await account.signTypedData({
  domain: { name: "Mneme", version: "1", chainId: 8453 },
  types:  { MnemeSession: [/* ... */] },
  primaryType: "MnemeSession",
  message: { wallet: address, issued_at, expires_at },
});

const { access_token } = await fetch("https://gateway.mnemedb.dev/sessions", {
  method: "POST",
  body:   JSON.stringify({ wallet, issued_at, expires_at, signature: sig }),
}).then((r) => r.json());

// 2. Use it as Bearer
const m = new Mneme({ accessToken: access_token, gatewayUrl: "..." });
\`\`\`

The dashboard uses this pattern (Privy embedded wallet signs once on load, then all calls are Bearer).
`,
  },

  // ─────────────────────────── OPERATE ─────────────────────────────────
  {
    id: "self-host",
    category: "Operate",
    title: "Self-host",
    content: `# Self-hosting

The whole gateway is ~1500 lines of TypeScript. Self-hosting is a 10-minute job.

## What you'll need

- A Postgres instance with the \`vector\` extension (Neon free tier works)
- Bun ≥ 1.1 (or Node 20 with the appropriate runner)
- Optional: Cloudflare R2 bucket for storage (or any S3-compatible)
- Optional: A Base RPC endpoint (defaults to \`mainnet.base.org\` — free, but rate-limited; use Alchemy/QuickNode for production)

## Setup

\`\`\`bash
git clone https://github.com/mnemedb/mnemedb
cd mnemedb
bun install

# gateway/.env
cat > gateway/.env <<EOF
DATABASE_URL=postgresql://...?sslmode=require
GATEWAY_JWT_SECRET=$(openssl rand -hex 32)
MNEME_DOMAIN_NAME=Mneme
MNEME_DOMAIN_VERSION=1
CHAIN_ID=8453
SIG_WINDOW_SECONDS=60
# Optional — storage:
R2_ACCOUNT_ID=...
R2_ACCESS_KEY_ID=...
R2_SECRET_ACCESS_KEY=...
R2_BUCKET=mneme-storage
R2_PUBLIC_BASE=https://cdn.example.com
# Optional — custom Base RPC:
BASE_RPC_URL=https://base-mainnet.g.alchemy.com/v2/...
EOF

bun run dev:gateway
# → mneme-gateway listening on :8787
\`\`\`

## Smoke test

\`\`\`bash
curl http://localhost:8787/health
# {"ok":true}

bun run scripts/smoke.ts
# walks through createProject → createTable → insert → list → vector search
\`\`\`

## Production deploy

The repo ships with a Dockerfile in \`gateway/\`. We deploy on DigitalOcean App Platform; Render / Fly.io / Railway all work the same way.

For the dashboard, \`dashboard/\` is a Vite app — \`bun run build\` produces a static site you can host anywhere (Vercel, Cloudflare Pages, DO Static Site).

DNS:
- \`gateway.yourdomain.tld\` → your gateway deployment
- \`cdn.yourdomain.tld\` → R2 bucket custom domain (if using storage)
- \`yourdomain.tld\` → dashboard
`,
  },

  {
    id: "faq",
    category: "Operate",
    title: "FAQ",
    content: `# FAQ

### Is this just a memory wrapper like Mem0?

No. Mem0 / Pinecone give you a fixed memory store. Mneme gives you a real Postgres schema you control. Create any tables you want at runtime, query with full SQL power, run vector search on any column.

### Do I need to know crypto?

No. Sign in with email, Google, X, or Apple. Privy creates an embedded wallet behind a passkey — you never see crypto UI unless you want to. The wallet only authenticates requests; we never ask for an onchain transaction (except for the optional $MNEME burn to extend storage).

### Where is my data?

On a Postgres + pgvector instance we manage (Neon, Frankfurt). Every project is a fully isolated schema (\`agent_<handle>\`). No shared rows, no cross-tenant access — enforced at the gateway level and by your wallet signature.

### Can I export my data?

Run \`SELECT * FROM <table>\` against the SQL editor and copy the result. A first-class export endpoint is on the Phase 2 roadmap.

### What's the rate limit?

120 requests/minute per wallet on the free tier. Burn $MNEME to extend storage and you also unlock the 1200 req/min tier.

### Are uploads versioned?

Not in Phase 1. Re-uploading the same key overwrites the previous content (and the quota delta is computed against the existing object size).

### Does Mneme ever sign a transaction on my behalf?

No. The gateway only verifies your signatures; it never holds a private key with funds. Every onchain action ($MNEME burn for storage) is signed by you directly.

### What chains are supported?

Base mainnet (chain id 8453) for auth and burns. Storage / Postgres are not chain-specific. Phase 2 may add additional chains for the onchain handle registry.

### Is the code open source?

Yes — MIT licensed at [github.com/mnemedb/mnemedb](https://github.com/mnemedb/mnemedb). Both the gateway and the dashboard.
`,
  },
];
